; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno_r4_minima]
platform = renesas-ra
board = uno_r4_minima
framework = arduino
monitor_speed = 115200
lib_deps = Audio
build_flags =
    -DSAMPLE_RATE_HZ=32000
    -Wl,-Map,firmware.map

[env:windows]
platform = native
build_flags =
    -DSAMPLE_RATE_HZ=32000
lib_deps = AudioWin, ArduinoWin